# Generated by Django 5.0.6 on 2024-07-13 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productosApp', '0002_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(12)]),
        ),
    ]
